version: "3.4"


services:
  mailer-front:
    build:
      context: ../
      dockerfile: ./development/mailer-front/Dockerfile
    volumes:
      - '../mailer-front/src:/usr/src/app/src'
      - '../mailer-front/public:/usr/src/app/public'
    ports:
      - "3000:3000"
    command: ["yarn", "start"]
  mailer-api:
    environment:
      - MAILGUN_URL=${MAILGUN_URL:?Please set MAILGUN_URL environment variable}
      - MAILGUN_KEY=${MAILGUN_KEY:?Please set MAILGUN_KEY environment variable}
      - SENDGRID_KEY=${SENDGRID_KEY:?Please set SENDGRID_KEY environment variable}
    build:
      context: ../
      dockerfile: ./development/mailer-api/Dockerfile
    volumes:
      - '../mailer-api:/usr/src/app/'
    ports:
      - "8080:8080"
    depends_on:
      - mailer-front
    command: ["uvicorn", "api.src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
